[package]
name = "lily"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies.ori]
git = "https://github.com/ChangeCaps/ori.git"
features = ["full"]

[profile.dev]
debug = false
